version: '3.9'

services:

  app:
    build:
      context: './'
      dockerfile: '.docker/app/Dockerfile'
    container_name: 'doika-app'
    restart: 'unless-stopped'
    working_dir: /app
    ports:
      - ${FORWARD_HTTP_PORT:-8080}:80
      - ${FORWARD_HTTPS_PORT:-4430}:443
    depends_on:
      - mysql
    volumes:
      - ./.docker/www:/var/www
      - ./public:/var/www/doika
      - ./:/app
      - ./.docker/app/config/apache/vhosts:/etc/apache2/sites-enabled
      - ./.docker/app/data/apache/logs:/var/log/apache2
      - ./.docker/app/config/php/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/app/data/composer/cache:/home/unicorn/.composer/cache:cached
    environment:
      IS_DOIKA_DOCKER_SETUP: 1

  mysql:
    image: mysql:5.7
    container_name: 'doika-mysql'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'mysqladmin', '-u$DB_USERNAME', '-p$DB_PASSWORD',  'ping', '-h', 'localhost']
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - ${FORWARD_DB_PORT:-33060}:3306
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    stop_grace_period: 1m

  node:
    image: node:lts-alpine
    container_name: 'doika-node'
    restart: unless-stopped
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
      - ./.docker/node/data/npm-cache:/root/.npm
      - ./.docker/node/data/logs:/root/.npm/_logs
